### ISSUE TITLE
Hardcode-Tray error

### ISSUE THREAD

**Issue by thegreatyellow67** [bil-elmoussaoui/Hardcode-Tray#476] opened 2017-12-18 10:35 UTC
### Specifications
- Hardcode-Tray version : 4.1-1
- Distribution : Manjaro Linux 17.1-rc1 Hakoila
- Gtk version : ``
- Inkscape version : 0.92.2 5c3e80d, 2017-08-06
- Cairo version : 1.15.8-2
- Sni-qt version: sni-qt-patched-git r.-1
- Application name :  ``
- Application version : ``

When I run hardcode-tray with command:
sudo -E hardcode-tray

and choice:
Welcome to Hardcode-Tray!
Desktop Environment: Xfce
Scaling Factor: 1
Icon Size: 24
Icon Theme: Papirus-Adapta-Nokto
Conversion Tool: Inkscape
To Do: All
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1

returns this error:
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 120, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 151, in do_action
    self.install()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/decorators.py", line 59, in wrapper
    func(app)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 97, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 51, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 66, in install_icon
    self.set_icon(icon, icon_path, png_bytes, True)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 48, in set_icon
    self.set_binary_file(path.join(str(icon_path), self.binary))
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 44, in set_binary_file
    self.pak = DataPack(binary_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py", line 32, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py", line 66, in _read
    raise Exception
Exception

what's wrong and how to fix it?
Thanks

**Comment by bil-elmoussaoui** [comment] 2017-12-18 13:25
The issue is caused by a new version of pak files (the format of the file, that chrome uses to store their assets). Recently, there was a new version. Which we tried to support in the master branch; but there's still an issue that we should fix #411. Once it's fixed we will release a new stable release.

In order to fix this, you will have to add `google-chrome` and `chromium` to your blacklist. See the readme for the config file information and how to use it.

Closing

**Closed by bil-elmoussaoui** 2017-12-18 13:25 UTC
