### ISSUE TITLE
SCRIPT EXECUTION FAILS  WITH ERROR NO ATTRIBUTE 'ANTIALIAS_FAST'

### ISSUE THREAD

**Issue by danielmwai** [bil-elmoussaoui/Hardcode-Tray#118] opened 2015-10-23 08:32 UTC
On executing  the  script  in  Fedora 23  x86_64   with  all  dependencies  of  this script  installed fails 
ERROR : 
-----------------
Traceback (most recent call last):
  File "script.py", line 25, in <module>
    svgtopng = load_source('svgtopng', './database/scripts/svgtopng.py')
  File "/usr/lib64/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "./database/scripts/svgtopng.py", line 8, in <module>
    from cairosvg import svg2png
  File "/usr/lib/python3.4/site-packages/cairosvg/__init__.py", line 27, in <module>
    from . import surface
  File "/usr/lib/python3.4/site-packages/cairosvg/surface/__init__.py", line 47, in <module>
    "optimizeSpeed": cairo.ANTIALIAS_FAST,
AttributeError: 'module' object has no attribute 'ANTIALIAS_FAST'

**Comment by bil-elmoussaoui** [comment] 2015-10-23 08:50
Are you using the latest version of the script ? Can you try installing inkscape and try again ?

**Comment by edgard** [comment] 2015-10-25 06:08
Same on Ubuntu Wily.

**Comment by wa4557** [comment] 2015-10-25 14:00
Should be working now, can someone try?

**Comment by bil-elmoussaoui** [comment] 2015-10-25 14:18
Works fine here! @edgard can you confirm that?

**Comment by edgard** [comment] 2015-10-25 19:53
I don't have Inkscape and with cairosvg only now it is giving the message:
"You need either a working python-cairosvg installation or inkscape installed. Exiting."

I've checked a little further and seems to be a upstream problem:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800882

With Inkscape is fine.

**Comment by bil-elmoussaoui** [comment] 2015-10-25 19:55
The only way to fix it was adding Inkscape support! I'm going to close this and hope they will fix this issue as soon as possible :+1:

**Closed by bil-elmoussaoui** 2015-10-25 19:55 UTC
Labels: bug

**Comment by edgard** [comment] 2015-10-25 20:10
Yeah, just confirmed, installing cairosvg 1.0.17 from ubuntu xenial with fixes the problem.
