### ISSUE TITLE
TeamViewer now native app

### ISSUE THREAD

**Issue by varlesh** [bil-elmoussaoui/Hardcode-Tray#470] opened 2017-12-05 06:45 UTC
https://community.teamviewer.com/t5/Linux/Update-TeamViewer-13/td-p/24537

**Comment by bil-elmoussaoui** [comment] 2017-12-08 17:07
Thanks for sharing this! I couldn't install it on Archlinux, is there a tray icon now?

**Comment by varlesh** [comment] 2017-12-10 07:39
Yes, used app icon from theme on tray:
![image](https://user-images.githubusercontent.com/8083855/33802989-7174361a-dd9e-11e7-82e7-166fd5f9fcbf.png)
Also need fix **StartUpWMClass**

**Comment by bil-elmoussaoui** [comment] 2017-12-15 15:54
If they use the same icon name as the application icon, the issue must be reported upstream then. Otherwise, we can do too much, as there's nothing but binary files. 
Anyway, i will try to install the beta on Ubuntu and see what i can do about that.

**Comment by wa4557** [comment] 2017-12-24 10:26
It's not using the same icon. The icon it uses is `TeamViewer` which is not the app icon

**Comment by bil-elmoussaoui** [comment] 2018-01-07 18:07
The icon names are still hardcoded. And the application even if it's a native one, still uses Qt, so it's either Qt5 then it's a duplicate of #293 or it's a qt4, and then we should see how to fix it like in here #163.

So, i'm going to close this issue as a duplicate, since the new version doesn't provide any way to fix the icons neither :( 
And we should really contact teamviewer devs and see if they would like to use to use the icons from the theme directly ;)

**Closed by bil-elmoussaoui** 2018-01-07 18:07 UTC
Labels: question

**Comment by sviperz** [comment] 2018-07-04 12:18
If any of you are interested https://community.teamviewer.com/t5/Linux/Theme-friendly-TeamViewer/m-p/37662

**Comment by bilelmoussaoui** [comment] 2018-07-04 12:29
@sviperz Thanks! Will check that and hope that TeamViewer team will be interested in making their app look a bit better.
