### ISSUE TITLE
Skype Notifications

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#59] opened 2015-07-09 17:15 UTC
When Skype gets a notification it's reverting to the default icon with the little orange dot rather than the blue status icon that this script switches it to

**Comment by bil-elmoussaoui** [comment] 2015-07-09 17:17
I will need the result of ```ls -R /tmp/sni-qt_*``` so i can check if the icon names are correct or not

**Comment by Foggalong** [comment] 2015-07-09 18:28
I've found this unthemed icon with the name `skype_18942_0fce05395e6040b3fd0838935b3aa115.png`. I'm guessing there'll be one of these icon for each number, but that they only show up after they've been seen for the first time?
![screenshot_2015-07-09_19-27-18](https://cloud.githubusercontent.com/assets/5920259/8603496/8c1ba422-2670-11e5-85e2-956da06d0db1.png)

**Comment by bil-elmoussaoui** [comment] 2015-07-09 18:58
Qt indicator uses tmp folder to store the icons. The icons will be shown in tmp once they're used and will be removed when you close the application. For example in this case you've ```skype_x_y.png```. In ```.local/share/sni-qt/icons/``` you will need to create a folder name ```skype``` and put the icon ```y.png``` there. The x changes in ```/tmp/``` whenever you reopen the application which makes it impossible to theme without the patched version of sni-qt. Can you share check if ```0fce05395e6040b3fd0838935b3aa115.png``` exists in ```.local/share/sni-qt/icons/skype/```?

**Comment by wa4557** [comment] 2015-07-09 19:02
It does but is a symlink. Maybe symlinks are no good? I can reproduce this btw. :(

**Comment by bil-elmoussaoui** [comment] 2015-07-09 19:04
This should be fixed now :P

**Comment by wa4557** [comment] 2015-07-09 19:31
No. Symlinks aren't the problem (at least for me). The same thing happens if all files are regular files...
![unbenannt](https://cloud.githubusercontent.com/assets/6475757/8604917/d71c10a4-2681-11e5-8273-678547659b0f.png)

**Comment by bil-elmoussaoui** [comment] 2015-07-09 19:33
Symlinks were not the problem, remove everything in ```.local/share/sni-qt/icons/skype``` and run the script again. This issue is due to some icons that were symlinked to themselves

**Comment by wa4557** [comment] 2015-07-09 19:35
Nope. Same as before...

**Comment by bil-elmoussaoui** [comment] 2015-07-09 19:49
Can you paste the list of icons in tmp/sni-qt_skype?

**Comment by wa4557** [comment] 2015-07-09 19:56
The problem is this not /tmp but there are a lot of icons missing, to which symlinks are pointing to, which breaks a lot of symlinks.

I tried to figur out why this happens, but no luck so far

```
0d96a65d843060dab4836712307a256b.png
fd56304306a9b229dbdaf4cf7dc4cbc7.png
4fb7a30c39fb0b95f300952ad4df27dc.png
```
are missing

**Comment by bil-elmoussaoui** [comment] 2015-07-09 20:12
@wa4557 can you try it now?

**Comment by wa4557** [comment] 2015-07-09 20:13
Ok the problem was that the script somehow corrupted the source icons in the icon theme (how can this possibly happen, the script only reads the file?). Anyways after repairing those files in the icon theme it works now

**Comment by wa4557** [comment] 2015-07-09 20:14
Is it possible, that the script tried to symlink a symlink back to the icon theme, and therefore broke the icon?

**Comment by bil-elmoussaoui** [comment] 2015-07-09 20:19
This is somehow possible :/ Because those broken icons were symlinked to themselves

**Comment by bil-elmoussaoui** [comment] 2015-07-09 20:20
@Foggalong can you confirm this?

**Comment by bil-elmoussaoui** [comment] 2015-07-14 15:30
Is this fixed or not yet?

**Comment by Foggalong** [comment] 2015-07-15 13:08
I don't actually get enough notifications to actually test this :(

**Comment by bil-elmoussaoui** [comment] 2015-07-15 13:11
I will keep this open until you test it :+1:

**Comment by Foggalong** [comment] 2015-07-16 16:55
First notification working! :D not sure if it works for if you have more than one notification though - don't know how high up Skypes icons for the counter go :/
![screenshot_2015-07-16_17-53-51](https://cloud.githubusercontent.com/assets/5920259/8729539/b5c9f42c-2be3-11e5-93be-eb65ef27642c.png)

**Comment by bil-elmoussaoui** [comment] 2015-07-16 16:56
Nice!! I will close this :+1:

**Closed by bil-elmoussaoui** 2015-07-16 16:56 UTC

**Comment by wa4557** [comment] 2015-07-16 19:44
Skype doesn't have a real counter for notifications. Even for more messages only the orange "1" is displayed
