### ISSUE TITLE
Skype and ownCloud not being fixed

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#111] opened 2015-10-11 13:18 UTC
This is the error I had after I fixed the dependency problem in #104. Both are sni-qt apps so it's possible the method has changed slightly between 15.04 and .10?

**Comment by bil-elmoussaoui** [comment] 2015-10-11 13:31
Try reverting the script and open skype/owncloud, go to /tmp/ and check if you will find the icons there ? If you do can you paste a screenshot and the icons names. If not it's might be a sni-qt issue

**Comment by wa4557** [comment] 2015-10-11 14:31
Maybe the patched sni-qt version doesn't work for 15.10 yet?

**Comment by Foggalong** [comment] 2015-10-11 15:37
Yeah, icons are still in `/tmp`. Below are the screenshots of the ownCloud and Skype icons.
![screenshot_2015-10-11_16-34-35](https://cloud.githubusercontent.com/assets/5920259/10417502/10249cba-7036-11e5-8d87-3e6d4b7d504c.png)
![screenshot_2015-10-11_16-34-11](https://cloud.githubusercontent.com/assets/5920259/10417501/1022db28-7036-11e5-87c4-3d83d28bd20b.png)

In the tree I've included everything related to sni-qt, including spotify which is still working fine after the update. Also, what's up with the empty Python sni-qt directory?

```
.
├── sni-qt_owncloud_30020-Ur9Mrq
│   └── icons
│       └── hicolor
│           ├── 128x128
│           │   └── apps
│           │       ├── owncloud_30020_23064844cb89c0654026212a3faa910f.png
│           │       ├── owncloud_30020_9d626aa048ccbd28c9a5bf6bbaadee43.png
│           │       └── owncloud_30020_a4d0f4e492fad2e38e62dc68de83aaa0.png
│           ├── 256x256
│           │   └── apps
│           │       ├── owncloud_30020_23064844cb89c0654026212a3faa910f.png
│           │       ├── owncloud_30020_9d626aa048ccbd28c9a5bf6bbaadee43.png
│           │       └── owncloud_30020_a4d0f4e492fad2e38e62dc68de83aaa0.png
│           ├── 32x32
│           │   └── apps
│           │       ├── owncloud_30020_23064844cb89c0654026212a3faa910f.png
│           │       ├── owncloud_30020_9d626aa048ccbd28c9a5bf6bbaadee43.png
│           │       └── owncloud_30020_a4d0f4e492fad2e38e62dc68de83aaa0.png
│           └── 64x64
│               └── apps
│                   ├── owncloud_30020_23064844cb89c0654026212a3faa910f.png
│                   ├── owncloud_30020_9d626aa048ccbd28c9a5bf6bbaadee43.png
│                   └── owncloud_30020_a4d0f4e492fad2e38e62dc68de83aaa0.png
├── sni-qt_python2.7_2420-Q9cO9G
│   └── icons
├── sni-qt_skype_1900-vmGxeS
│   └── icons
│       └── hicolor
│           └── 24x24
│               └── apps
│                   ├── skype_1900_0972e5fde53a4a87346ebb91c4c2b159.png
│                   ├── skype_1900_2d1ee5482260fd9cd180b32787792683.png
│                   ├── skype_1900_37e170fc54e7355d9d298917e74f9ea9.png
│                   ├── skype_1900_602c84fa0f4d61c64f770495a500279e.png
│                   ├── skype_1900_6cbeda8e2c9f56d3ac75ccdf8d282a69.png
│                   ├── skype_1900_dad77418071bead905e2dbe605715dcd.png
│                   └── skype_1900_f2fc4a539a7b9553f5b35241d1154e84.png
├── sni-qt_spotify_28802-n8m06g
│   └── icons
│       └── hicolor
│           └── 22x22
│               └── apps
│                   └── spotify_28802_c71dab2862193f4207827dfaecf3818e.png
├── sni-qt_spotify_28966-f7d6OJ
│   └── icons
│       └── hicolor
│           └── 22x22
│               └── apps
│                   └── spotify_28966_c71dab2862193f4207827dfaecf3818e.png

```

**Comment by bil-elmoussaoui** [comment] 2015-10-11 15:40
Oh! i didn't think that we can fix Spotify using sni-qt too :D i will check this later :)

**Comment by Foggalong** [comment] 2015-10-11 15:44
Spotify is already fixed so that's not a problem :)

**Comment by bil-elmoussaoui** [comment] 2015-10-11 16:05
Can you check if there's any icons in `$HOME/.local/share/sni-qt`?

**Comment by Foggalong** [comment] 2015-10-11 16:18
Nothing in that folder at all

**Comment by bil-elmoussaoui** [comment] 2015-10-11 18:13
I forgot that you reverted the icons :p try applying again and see if there's any icons? if there's check in the tmp folder;
btw, i have the same issue here in ubuntu 15.10, i think the issue is due to sni-qt :/

**Comment by wa4557** [comment] 2015-10-11 18:40
Have you tried installing the 15.04 sni-qt version?

**Comment by bil-elmoussaoui** [comment] 2015-10-11 18:42
@cybre I just wanted to ask you as you're the maintainer of the PPA we're using, is there any issue like that in Sni-qt? or maybe a newer version of sni-qt? Thanks!

**Comment by Foggalong** [comment] 2015-10-11 18:43
Files are still all there after applying again.

**Comment by cybre** [comment] 2015-10-11 21:39
@Foggalong My PPA says there is a newer sni-qt available si you probably have the wrong version of sni-qt installed.
What's the output of `dpkg --list sni-qt`?

I'll try upping the version to fix the problem.

**Comment by Foggalong** [comment] 2015-10-12 18:53
```
ii  sni-qt:amd64   0.2.7+15.10. amd64        indicator support for Qt
ii  sni-qt:i386    0.2.7+15.10. i386         indicator support for Qt
```

**Comment by cybre** [comment] 2015-10-12 20:15
Yup, wrong version.

**Comment by cybre** [comment] 2015-10-12 20:21
I'm currently trying with a higher version number.

**Comment by cybre** [comment] 2015-10-12 20:37
@Foggalong Please try [this PPA](https://code.launchpad.net/~cybre/+archive/ubuntu/sni-qt-testing) and let me know if it works so I can push the new version to the main PPA.

**Comment by Foggalong** [comment] 2015-10-12 21:49
@cybre New package working just fine :+1:

**Comment by bil-elmoussaoui** [comment] 2015-10-13 16:34
Should be fixed with the latest update of the stable PPA! Thank you @cybre !

**Closed by bil-elmoussaoui** 2015-10-13 16:34 UTC
Labels: bug
