### ISSUE TITLE
Messed with .local folder

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#246] opened 2016-12-11 18:16 UTC
In continuation of [this comment](https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/226#issuecomment-266094976), using [this PPA](https://code.launchpad.net/~andreas-angerer89/+archive/ubuntu/sni-qt-patched) has seriously fucked with my system. The permissions for the `~/.local` folder had been changed so that it was no longer accessible to anything but the root user which is why programs like ownCloud & Thunar stopped functioning properly.

This was on Ubuntu 16.10 with PPA versions of both the script and SNI-Qt.

**Comment by bil-elmoussaoui** [comment] 2016-12-12 02:54
It's a duplicate of #241. i will push a fix tomorrow

**Closed by bil-elmoussaoui** 2016-12-12 02:54 UTC
