### ISSUE TITLE
Rambox No Longer Fixed

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#373] opened 2017-06-02 08:08 UTC
### Specifications
- Hardcode-Tray version : 3.8.2
- Distribution : Ubuntu 17.04
- Gtk version : 3.22
- Application name :  Rambox
- Application version : 0.5.9

### Expected behavior and actual behavior

Expect it to fix the Rambox tray icon, doesn't fix the Rambox tray icon. 

### Steps to reproduce the problem
1. Install latest version of Rambox
2. Install latest version of HC-T
3. Run HC-T

**Comment by Foggalong** [comment] 2017-06-02 08:09
For clarification, the exact same version HC-T running on the same system correctly fixed the previous version (0.5.3) of Rambox.

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:20
I've just downloaded the same version as you and it works without any problem. How did you installed this version?

**Comment by Foggalong** [comment] 2017-06-02 08:26
Just `dpkg -i`'d the deb file that the internal updater prompted me to download

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:29
What's the output of `hardcode-tray --apply --only rambox`? Also can you get me the latest log file in /tmp/Hardcode-Tray after you have executed the command

**Comment by Foggalong** [comment] 2017-06-02 08:30
Output:

![screenshot_2017-06-02_09-29-02](https://cloud.githubusercontent.com/assets/5920259/26717609/eda9f4be-4775-11e7-9e21-dd4ea9ba01c7.png)

Log:

![screenshot_2017-06-02_09-30-18](https://cloud.githubusercontent.com/assets/5920259/26717668/1eb15ca0-4776-11e7-811f-4a37e1a73cd8.png)

**Comment by Foggalong** [comment] 2017-06-02 08:33
I've just realised that it's detecting Adwaita as my theme when it's actually Numix. Rerunning with the `--theme Numix` flag successfully fixed Rambox. That means it's a problem with the theme not being correctly detected :confused:

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:33
What distro are you using ?  `echo $XDG_CURRENT_DESKTOP`
And do you have any idea of the exact path on dconf of the icon theme ?
The issue is due to the icon theme not being detected correctly. You can use `--theme Numix` to fix that or use the config.json file so you will never have to worry about that.

**Comment by Foggalong** [comment] 2017-06-02 08:36
Distro is Xubuntu 17.04 with i3 as the window manager. Running `echo $XDG_CURRENT_DESKTOP` returns `i3` but the icon theme is being applied via the XFCE settings rather than i3 config.

**Comment by Foggalong** [comment] 2017-06-02 08:36
@bil-elmoussaoui The script is also claiming that it's fixing ownCloud when it's not. Should I open a new issue for that?

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:37
Alright, can you open dconf and see where the icon is stored ? i've never used xfce before...

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:37
Do you mean that it shouldn't say that it's fixing owncloud because you don't have it installed on your system or the icons doesn't change ?

**Comment by Foggalong** [comment] 2017-06-02 08:45
There's `org.gnome.desktop.interface.icon-theme` but that's currently set to Adwaita so that's clearly not how the theme is being applied here.

And yeah: hardcode-fix says it's been fixed, but the icons are remaining the same.

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:47
The OwnCloud issue is known, they're using Qt5 instead of Qt4 and there's an open issue about that #293 
Well, if you don't know which gsettings path is being used i think you will have to live with that until someone else knows :p:

**Comment by bil-elmoussaoui** [comment] 2017-06-02 08:52
Here's what defines where to look for the icon theme https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/src/const.py#L44

**Comment by bil-elmoussaoui** [comment] 2017-06-02 09:01
I think i've figured it out 
`xfconf-query -c xsettings -p /Net/IconThemeName -s` should return the icon theme on xfce, but why your XDG_CURRENT_DESKTOP returns i3?

**Comment by Foggalong** [comment] 2017-06-02 09:02
I think the whole point is that it's not a gsettings path. I've found where the icon theme setting is referred to: the file `~/.config/gtk-3.0/settings.ini` has the line `gtk-icon-theme=Numix Circle`. That file seems to contain all the settings set by lxappearance, and according to the [Arch Linux wiki](https://wiki.archlinux.org/index.php/GTK%2B#Configuration) looks to be the standard way to change GTK settings.

**Comment by Foggalong** [comment] 2017-06-02 09:03
The `-s` in the command above sets that setting, you need to run it without that to find what value is currently set.

**Comment by bil-elmoussaoui** [comment] 2017-06-02 09:04
*it must -v sorry

**Comment by Foggalong** [comment] 2017-06-02 09:06
I can't see what it originally said anymore because when I copy pasted your command I accidentally had a "Numix" left over from a previous grep command, so because of your `-s` the icon theme was set to "Numix" and the previous setting lost :confused: 

However I'm fairly sure it's the ~/.config/gtk-3.0/settings.ini` which is changing the theme

**Comment by bil-elmoussaoui** [comment] 2017-06-02 09:08
Does this works with only XFCE or i3 too?

**Comment by Foggalong** [comment] 2017-06-02 09:11
Yeah it is. If I set the theme to Numix then both `~/.config/gtk-3.0/settings.ini` and `xfconf-query -c xsettings -p /Net/IconThemeName -s` say that the theme is Numix.

![screenshot_2017-06-02_10-08-24](https://cloud.githubusercontent.com/assets/5920259/26719217/8eeb3c34-477b-11e7-8178-ad48b53411b8.png)

If I then apply Numix Circle `~/.config/gtk-3.0/settings.ini` confirms that the new icon theme is "Numix Circle" while `xfconf-query -c xsettings -p /Net/IconThemeName -s` still says it's "Numix" from when I accidentally set it above.

![screenshot_2017-06-02_10-09-40](https://cloud.githubusercontent.com/assets/5920259/26719260/ba49b25c-477b-11e7-857f-75a681f7f1fe.png)

So it's definitely the value in `~/.config/gtk-3.0/settings.ini` which is the currently applied icon theme. Are you asking me if this is something specific to XFCE, i3, or both?

**Comment by bil-elmoussaoui** [comment] 2017-06-02 09:14
Yep, because i don't want to force users to use that if it shouldn't be used. The same file seems to be used on KDE & Deepin too.
So, elementary, GNOME & Solus uses the gsettings value  & the rest uses that file ?

**Comment by Foggalong** [comment] 2017-06-02 09:15
I'll have to run up a fresh VM later to check, but it sounds like if it's the case for KDE & Deepin, it probably will be for i3 & XFCE. The pattern looks to be those that have heavy GTK integration use gsettings, those that don't use settings.ini

**Comment by bil-elmoussaoui** [comment] 2017-06-02 09:39
Fixed on master https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/49ae80e9629e669b5144f950115f1be6ec0c3dd6

**Closed by bil-elmoussaoui** 2017-06-02 09:39 UTC
Labels: bug

**Comment by bil-elmoussaoui** [comment] 2017-06-19 23:03
@Foggalong I've pushed a much better fix to master if you have some free time to test it that would be really helpful. Thanks
