### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by navdeepio** [bil-elmoussaoui/Hardcode-Tray#458] opened 2017-11-11 14:12 UTC
### Specifications
- Hardcode-Tray version : `4.1.1`
- Distribution : `Antergos`
- Gtk version : `latest`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  ``
- Application version : ``

### Expected behavior and actual behavior
sudo hardcode-tray --apply results in a python exception

Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: Papirus
Conversion Tool: CairoSVG
To Do: All
Applying now..

Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 120, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 120, in execute
    delta = app.do_action(action)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 151, in do_action
    self.install()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/decorators.py", line 59, in wrapper
    func(app)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/application.py", line 97, in install
    self.execute(Action.APPLY)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/binary.py", line 51, in execute
    self.install_icon(icon, icon_path)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 66, in install_icon
    self.set_icon(icon, icon_path, png_bytes, True)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 48, in set_icon
    self.set_binary_file(path.join(str(icon_path), self.binary))
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/pak.py", line 44, in set_binary_file
    self.pak = DataPack(binary_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py", line 32, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/applications/helpers/data_pack.py", line 66, in _read
    raise Exception
Exception

### Steps to reproduce the problem
1. Install hardcode-tray on archlinux
2. sudo hardcode-tray --apply

**Comment by bil-elmoussaoui** [comment] 2017-11-11 14:16
It's a duplicate of #451 
Can you please send me the resources.pak file, you can find that in /opt/google/chrome/resources.pak by email
bil[dot]elmoussaoui[at]gmail[dot]com
I will try to reproduce it and fix it today :+1:

**Closed by bil-elmoussaoui** 2017-11-11 14:16 UTC
