### ISSUE TITLE
Remove extension from icons?

### ISSUE THREAD

**Issue by wa4557** [bil-elmoussaoui/Hardcode-Tray#45] opened 2015-07-05 08:24 UTC
When looking at for example the flarget database file it looks something like this:

```
300c99bb493a7061e9852c73b89a09e4.png, flareget-panel.svg, qt-tray
```

Since HC-tray fixer is in principle a theme agnostic tool, shouldn't the `.svg` be removed from the second column? It is irrelevant because we are splitting it afterwards and throwing it away anyways

**Comment by bil-elmoussaoui** [comment] 2015-07-05 11:46
for the ```Qt``` applications we can remove the extension, and i don't think that we can do that for the rest of applications. As we can not symlink/copy png icons and the application uses svg ones, correct me if i'm wrong

**Comment by wa4557** [comment] 2015-07-05 11:53
But the only important thing is the icon Name not the extension (that's of course only true for the second column)

**Comment by bil-elmoussaoui** [comment] 2015-07-05 11:55
I forgot that the second column is for the symlink icon name :+1:

**Comment by bil-elmoussaoui** [comment] 2015-07-05 12:00
Done in my latest commit

**Comment by wa4557** [comment] 2015-07-05 12:03
The question is: Is there something that needs to be changed in the script as well?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 12:10
Yeah, there's something that does not work when i run the script. It's due to ```extension_orig``` as the new icon name does not have any extension

**Comment by wa4557** [comment] 2015-07-05 12:32
Everything works for me!?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 14:41
Do you have telegram? It's not working here :/

**Comment by wa4557** [comment] 2015-07-05 14:52
I guess there are some fundamental problems when computing `extension_orig` there's something fishy there

**Comment by bil-elmoussaoui** [comment] 2015-07-05 15:15
I did some tests, the problem is in 
```theme_icon = theme.lookup_icon(base_icon, default_icon_size, 0)```
even if the icon do exists, the result of theme_icon is a  ```None```

**Comment by wa4557** [comment] 2015-07-05 15:17
No. I think the problem is that base_icon and extension_orig should be computed with symlink icon instead of icon I think

**Comment by bil-elmoussaoui** [comment] 2015-07-05 15:21
Indeed, the ```extension_org``` must have the extension of the symlink icon. But that won't solve the problem..
i'm getting this when the script tries to fix telegram 
```
Traceback (most recent call last):
  File "script.py", line 189, in <module>
    copy_files()
  File "script.py", line 161, in copy_files
    convert2svg(filename,output)
  File "script.py", line 113, in convert2svg
    svg = content_file.read()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by wa4557** [comment] 2015-07-05 15:27
oO on my machine this works. This seems to be a svg error? there is an error o the convert2svg formula

**Comment by bil-elmoussaoui** [comment] 2015-07-05 15:44
@wa4557 I think so as the error is in the svg file, when i do print the ```filename``` and ```øutput_file``` everything looks fine to me

**Comment by wa4557** [comment] 2015-07-05 15:54
Does the telegram svg looks ok in the numix-base theme?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 16:19
Yeah, before removing the extension the script was working fine

**Comment by wa4557** [comment] 2015-07-05 16:39
I think that was a coincidence. It was definitely wrong before as well

Bilal Elmoussaoui <notifications@github.com> schrieb am So., 05.07.2015,
18:19:

**Comment by wa4557** [comment] 2015-07-05 17:23
The question is:why is it even calling this function? Arent both svgs?  That's prltobably also the reason it breaks

**Comment by bil-elmoussaoui** [comment] 2015-07-05 17:24
Nop, the original icons are svg but the symlink icons are png

**Comment by wa4557** [comment] 2015-07-05 17:39
Does it work now with the PR merged?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 17:42
Nop still the same issue..:/

**Comment by wa4557** [comment] 2015-07-05 17:44
Weird it works perfectly for me. Can you try something like (i the path of the Hardcode tray fixer `python3 ./database/scripty/svg2png.py /usr/share/icons/Numix/22x22/status/telegram-pane.svg ~/test.png`?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 17:48
```
 File "svg2png.py", line 10, in <module>
    svg = content_file.read()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
``` 
The same thing

**Comment by wa4557** [comment] 2015-07-05 17:49
Ok and with any other svg?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 17:51
Works fine converting owncloud svg icons to png..this only happens with telegram icons

**Comment by wa4557** [comment] 2015-07-05 17:53
Tried reinstall numix?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 18:01
I just did that, the only icon that was fixed this time is : ```telegram -- fixed using /usr/share/icons/Numix/22x22/status/telegram-panel.svg
```

**Comment by wa4557** [comment] 2015-07-05 18:05
the only difference between your computer and mine is, that since you are using elementaryOS you are using the 24x24 panels, I'm using the 22x22 ones. Have you tried deleting the icons before reinstalling? I think a reinstall doen't necessarily overwrites all the files

**Comment by bil-elmoussaoui** [comment] 2015-07-05 18:10
It's not the case.. the icons used are 22x22 instead of 24x24

**Comment by wa4557** [comment] 2015-07-05 18:19
Can you open the file in inkscape?

**Comment by bil-elmoussaoui** [comment] 2015-07-05 18:23
This is fixed now, the issue was the icon size?? i fixed the issue with pantheon as the icons must be 24x24 and now everything works fine

**Comment by bil-elmoussaoui** [comment] 2015-07-05 18:24
and when i try to open using inkscape ```/usr/share/icons/Numix/22x22/status/telegram-attention-panel.svg``` i got an error

**Comment by wa4557** [comment] 2015-07-05 18:38
Ok But that means that you somehow corrupted your svg. No Bug in the script

Bilal Elmoussaoui <notifications@github.com> schrieb am So., 05.07.2015,
20:24:

**Comment by bil-elmoussaoui** [comment] 2015-07-05 20:07
Yeah, thanks

**Closed by bil-elmoussaoui** 2015-07-05 20:07 UTC
