### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by SteamEmix** [bil-elmoussaoui/Hardcode-Tray#279] opened 2017-01-06 02:22 UTC
Pidgin, Jetbrains Toolbox, Caffeine-ng

**Comment by varlesh** [comment] 2017-01-06 02:23
pidgin and caffeine worked from icon theme, hardcode-tray not needed

**Comment by bil-elmoussaoui** [comment] 2017-01-06 02:33
Jetbrain Toolbox has everything hardcoded on it's binary :(

**Comment by SteamEmix** [comment] 2017-01-09 18:28
varlesh
Well, I have something not working

**Comment by bil-elmoussaoui** [comment] 2017-01-09 18:37
Please provide the information asked for on the issue template... Otherwise I can't reproduce your issue in order to fix it

**Comment by SteamEmix** [comment] 2017-01-11 18:08
![111](https://cloud.githubusercontent.com/assets/4332540/21860521/a5da790c-d839-11e6-9c9e-3082717bd817.png)

**Comment by bil-elmoussaoui** [comment] 2017-01-11 18:23
@SteamEmix i need more than just a screenshot :) it would be cool if you can provide the informations asked for once you create a new issue (gtk version, icon theme, distro, desktop env...) otherwise i can't help you fix that ;)

**Comment by SteamEmix** [comment] 2017-01-11 18:55
@bil-elmoussaoui
 Hardcode-Tray version : v3.6.4
Distribution : Arch Linux KDE 64-bit
Plasma version : 5.8.5-1
I am also using:
-- Breeze dark theme
-- Papirus-Dark icon theme
-- Capitaine cursor theme


Properly and the all the information I provided? :))

**Comment by bil-elmoussaoui** [comment] 2017-01-11 19:15
Perfect! just need the applications versions so i can install them on my system and see how to fix that ;) anyway, jetbrains toolbox is a won't fix as we can't modify the binary's files

**Comment by SteamEmix** [comment] 2017-01-11 21:39
@bil-elmoussaoui 
Sorry but I just started to use and do github not fully know how to describe it :) and narahunok jetbrains tulboh nychoho okay :)) Consider the second time and will properly describe it :))

**Comment by bil-elmoussaoui** [comment] 2017-01-11 21:43
@SteamEmix it's okay :) all i need is the the application version so i can test that?

**Comment by SteamEmix** [comment] 2017-01-11 22:48
@bil-elmoussaoui 
I meant that I will now correctly execute :))

if you have inmind version of Pidgin 2.11.0 it
if you need any more then I tell you to write

**Comment by bil-elmoussaoui** [comment] 2017-01-13 07:50
Pidgin is not hardcoded at all, it using the icon theme. I checked the source code and tried with the same version as you. using both Papirus and Numix. If the icon theme you're using does not provide the tray icon please report it upstream. Closing

**Closed by bil-elmoussaoui** 2017-01-13 07:50 UTC
Labels: information needed
