### ISSUE TITLE
Hardcode-Tray not working!

### ISSUE THREAD

**Issue by Armanmd** [bil-elmoussaoui/Hardcode-Tray#415] opened 2017-08-04 16:26 UTC
### Specifications
- Hardcode-Tray version : `latest version on the github (4.1)`
- Distribution : `Linux Kali 4.9.0-kali3-686-pae #1 SMP Debian 4.9.18-1kali1 (2017-04-04) i686 GNU/Linux
`
- Gtk version : `3.22`
- Inkscape version : `` if installed
- Cairo version : `` if installed
- Sni-qt version: `` if installed
- Application name :  `telegram (v:1.1.10-1b) and rhythmbox (v:3.4.1) on the top panel`
- Application version : `latest version on the sources.list`v
- I am also using:
-- 'Topicons Plus' shell extension
-- 'Dash to panel' shell extension
-- numix icon theme

The program was not installed on the kali rolling before, but it is now installed
**_The Hardcode-Tray does not work in kali_** 

[screen shot](https://ibb.co/kGWZ4v)

**Comment by bil-elmoussaoui** [comment] 2017-08-04 16:40
Please provide more information and create a specific and detailed issue instead of saying that it doesn't work. What does not work ? I need the logs from /tmp/Hardcode-Tray.

**Comment by Armanmd** [comment] 2017-08-05 08:08
**_Please take a look at the screen shot. When I execute the command (sudo -E hardcode-tray), no icons will change in the top panel_** 
**_And this is my Hardcode-Tray log :_**

_https://picload.org/view/rwdwalir/screenshot-20170804121720-1366.png.html_
or
_https://ibb.co/kGWZ4v_
```
[DEBUG] 2017-08-05 03:59:02 DE: Gnome
[DEBUG] 2017-08-05 03:59:02 Config file: Not found.
[DEBUG] 2017-08-05 03:59:02 Arguments/Icon Size: None
[DEBUG] 2017-08-05 03:59:02 System/Icon Size: 22
[DEBUG] 2017-08-05 03:59:03 System/Theme: Numix-Circle
[DEBUG] 2017-08-05 03:59:03 Arguments/Conversion Tool: None
[DEBUG] 2017-08-05 03:59:03 Config/Conversion Tool: None
[DEBUG] 2017-08-05 03:59:03 SVG Factory: Import Inkscape
[DEBUG] 2017-08-05 03:59:09 Path with condition: dropbox_callback /home/root/.dropbox-dist/{dropbox}/images/hicolor/16x16/status/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/chromium/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/google-chrome/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/google-chrome-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/google-chrome-unstable/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/vivaldi/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/vivaldi-beta/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:09 Path with condition: hangouts_callback /home/root/.config/vivaldi-snapshot/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/{hangouts}/images_5/
[DEBUG] 2017-08-05 03:59:10 Config/Backup Ignore: False
[DEBUG] 2017-08-05 03:59:10 Create new backup folder for Keepassx
[DEBUG] 2017-08-05 03:59:10 Creating directory: /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10/
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10
[DEBUG] 2017-08-05 03:59:10 Backup file: /usr/share/keepassx/icons/keepassx.png to: /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10/keepassx.png
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10
[DEBUG] 2017-08-05 03:59:10 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10/keepassx.png
[DEBUG] 2017-08-05 03:59:10 Executing command: inkscape -z -f /usr/share/icons/Numix/22/status/keepassx-indicator.svg -e /usr/share/keepassx/icons/keepassx.png -w 22 -h 22
[DEBUG] 2017-08-05 03:59:12 Backup file: /usr/share/keepassx/icons/keepassx_locked.png to: /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10/keepassx_locked.png
[DEBUG] 2017-08-05 03:59:13 Executing command: chmod 0777 /home/root
[DEBUG] 2017-08-05 03:59:13 Executing command: chmod 0777 /home/root/.config
[DEBUG] 2017-08-05 03:59:13 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray
[DEBUG] 2017-08-05 03:59:13 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx
[DEBUG] 2017-08-05 03:59:13 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10
[DEBUG] 2017-08-05 03:59:13 Executing command: chmod 0777 /home/root/.config/Hardcode-Tray/Keepassx/05-08-2017_03-59-10/keepassx_locked.png
[DEBUG] 2017-08-05 03:59:13 Executing command: inkscape -z -f /usr/share/icons/Numix/22/status/keepassx-locked.svg -e /usr/share/keepassx/icons/keepassx_locked.png -w 22 -h 22
```
what to do ?

**Comment by bil-elmoussaoui** [comment] 2017-08-05 11:24
I see that  Telegram is not detected correctly. It must be that Telegram is installed in a different location on Kali Linux. Can you see if any folder from app_path or icons_path exists? if not please create a PR with the correct paths in Kali Linux https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/database/telegram.json

For the other tray icon, I don"t think that we support it. Would you please next time provide the apps names? It's much easier.
+ You can add the screenshots directly to the Github issues/comments by drag/drop the images. I won't look at any image from any external link in the future;

**Comment by Armanmd** [comment] 2017-08-06 12:52
# Hello
**Thanks** for the **reply**
**_I installed the telegram software from Kali Tanks_**
![](http://i.imgur.com/EYMxSfI.png)
Installed Files locations:
```
/.
/usr
/usr/bin
/usr/bin/telegram-desktop
/usr/share
/usr/share/applications
/usr/share/applications/telegramdesktop.desktop
/usr/share/doc
/usr/share/doc/telegram-desktop
/usr/share/doc/telegram-desktop/README.Debian
/usr/share/doc/telegram-desktop/README.md
/usr/share/doc/telegram-desktop/TODO.Debian
/usr/share/doc/telegram-desktop/changelog.Debian.gz
/usr/share/doc/telegram-desktop/changelog.Debian.i386.gz
/usr/share/doc/telegram-desktop/changelog.gz
/usr/share/doc/telegram-desktop/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/128x128
/usr/share/icons/hicolor/128x128/apps
/usr/share/icons/hicolor/128x128/apps/telegram.png
/usr/share/icons/hicolor/16x16
/usr/share/icons/hicolor/16x16/apps
/usr/share/icons/hicolor/16x16/apps/telegram.png
/usr/share/icons/hicolor/256x256
/usr/share/icons/hicolor/256x256/apps
/usr/share/icons/hicolor/256x256/apps/telegram.png
/usr/share/icons/hicolor/32x32
/usr/share/icons/hicolor/32x32/apps
/usr/share/icons/hicolor/32x32/apps/telegram.png
/usr/share/icons/hicolor/512x512
/usr/share/icons/hicolor/512x512/apps
/usr/share/icons/hicolor/512x512/apps/telegram.png
/usr/share/icons/hicolor/64x64
/usr/share/icons/hicolor/64x64/apps
/usr/share/icons/hicolor/64x64/apps/telegram.png
/usr/share/kde4
/usr/share/kde4/services
/usr/share/kde4/services/tg.protocol
/usr/share/man
/usr/share/man/man1
/usr/share/man/man1/telegram-desktop.1.gz
```
What if I want to install manually? What should I do?

**Comment by bil-elmoussaoui** [comment] 2017-08-08 14:33
Telegram stores the icons here `$HOME/.local/share/TelegramDesktop/tdata/ticons/` If you don't find any icon. You must be missing libappindicator or an other dependency in your installation system

**Comment by Armanmd** [comment] 2017-08-09 11:25
@bil-elmoussaoui Hi, I found the location

![](http://i.imgur.com/IruLYyp.png)

what to do ?

i think Hardcode-Tray not working on the Debian Maschine ؟

Have you tried on Debian?

**Comment by bil-elmoussaoui** [comment] 2017-08-09 11:34
Again the issue is due to having root as a username :( Hardcode-Tray was never tested in such case. The location is not found because the home location is not detected correctly. I'm not going to do any modifications at the moment to make things works as this might break stuff. But this should be fixed once #397. If you don't want to wait. Just edit `const.py` can be found in `/usr/lib/python3.5 or 3.6/site-packages/HardcodeTray/`and replace `USERHOME = get_userhome(USERNAME)` by the path to your userhome (the output of $HOME in terminal).

**Comment by Armanmd** [comment] 2017-08-09 14:00
@bil-elmoussaoui **_Thanks_** for the **_reply_**
![screenshot from 2017-08-09 09-56-26](https://user-images.githubusercontent.com/29518463/29125236-376240f4-7ce9-11e7-9dcc-00022c8ed427.png)
 **_i try on another user wroked as well so if i  want use hardtray on the root user what must i do_**

the output of $HOME in terminal is 
:bash: /root: Is a directory
USERHOME = /root (notworking)

**Comment by bil-elmoussaoui** [comment] 2017-08-09 14:59
You must use "", something more like `USERHOME = "/root" or whatever the output you've got from `$HOME`

**Comment by Armanmd** [comment] 2017-08-10 12:12
@bil-elmoussaoui output not working plz check this image

![](http://i.imgur.com/DNSqnqU.png)

**Comment by Armanmd** [comment] 2017-08-10 12:13
![](http://i.imgur.com/CNaD4VT.png)

**Comment by bil-elmoussaoui** [comment] 2017-08-10 12:57
Fixed that issue on master https://github.com/bil-elmoussaoui/Hardcode-Tray/commit/4cd44cec3fc72f0a948550f98feb87bcd813d6df
The userhome/username should be detected correctly now

It's up to Numix theme to support that, open a new issue about that upstream. 
Closing

**Closed by bil-elmoussaoui** 2017-08-10 12:57 UTC
Labels: information needed
