### ISSUE TITLE
chromium indicator and hangouts (plugin of chromium) indicator is not monochrome

### ISSUE THREAD

**Issue by raknerak** [bil-elmoussaoui/Hardcode-Tray#77] opened 2015-08-10 05:36 UTC
![selection_020](https://cloud.githubusercontent.com/assets/7880734/9159938/e7ba4ba2-3f3a-11e5-8634-99312918a615.png)
- [x] Hangouts plugin indicator
- [x] Chromium indicator

**Comment by bil-elmoussaoui** [comment] 2015-08-10 05:43
Well, i'm going to give it a try. How do you installed Chromuim? The distro you're using?

**Comment by raknerak** [comment] 2015-08-10 05:44
yes I installed chromium from ubuntu software center. I am using ubuntu 14.04

**Comment by bil-elmoussaoui** [comment] 2015-08-10 06:04
I will install it today ;)

**Comment by bil-elmoussaoui** [comment] 2015-08-10 22:38
tried it, but that does not show me any indicator :/

**Comment by raknerak** [comment] 2015-08-11 05:07
İf you install hangouts(old name gtalk)  add on on chromium, indicator
appears

On Tuesday, August 11, 2015, Bilal Elmoussaoui <notifications@github.com>
wrote:

> tried it, but that does not show me any indicator :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/77#issuecomment-129635635>
> .
>


-- 
Ahmet Yıldırım

**Comment by bil-elmoussaoui** [comment] 2015-08-12 20:44
Thanks for the informations. I think i know how to deal with those icons (the hangout icon does not appear in my case); but i will give it my best once this issue is fixed #75

**Comment by wa4557** [comment] 2015-08-12 20:57
@bil-elmoussaoui if you add this addon the icon appears https://chrome.google.com/webstore/detail/hangouts/nckgahadagoaajjgafhacjanaoiihapd/related?hl=en

**Comment by bil-elmoussaoui** [comment] 2015-08-12 20:59
Ah It's :p I was testing on the new Gnome indicator icons and it's not working; i just installed unity to test it. Thanks

**Comment by wa4557** [comment] 2015-08-12 21:01
I really like google products (or is it alphabet now:P), but they seem to have problems with themable icons

**Comment by bil-elmoussaoui** [comment] 2015-08-12 21:03
I do use google products too; i hope they will do something in the near future ;)

**Comment by wa4557** [comment] 2015-08-12 21:06
@raknerak How did you manage to move the hangouts icon to the left? I can't move it by changing its value in `ordering-override.keyfile`

**Comment by bil-elmoussaoui** [comment] 2015-08-13 09:01
@raknerak can you try the latest version of the script after reinstalling Chromuim and see if the script works fine with Chromuim too?

**Comment by raknerak** [comment] 2015-08-13 09:07
I tried, indicator (systream tray) is the same and also theme seems broken as following:

![selection_027](https://cloud.githubusercontent.com/assets/7880734/9246381/dc3865a4-41b3-11e5-92ad-59d6330f3da3.png)

**Comment by wa4557** [comment] 2015-08-13 09:08
Nooooooo :(

**Comment by bil-elmoussaoui** [comment] 2015-08-13 09:43
You've removed everything in the older folder? i mean here `/usr/lib/chromium-browser` can you remove chromuim,  use `sudo rm -rf /usr/lib/chromium-browser/` , reinstall again, and then try again?

**Comment by raknerak** [comment] 2015-08-13 10:04
I tired but now hangouts is chrashing. I tried to rollback problem by removing-purging chromium and re-installing extension but still not fixed.

![selection_031](https://cloud.githubusercontent.com/assets/7880734/9247454/c7bbee90-41bb-11e5-9ff6-31a33b5baf72.png)

**Comment by bil-elmoussaoui** [comment] 2015-08-13 10:13
What about trying Google Chrome ? i think i know why.. i will try to fix it next week

**Comment by raknerak** [comment] 2015-08-13 10:35
Hi Bilal,

I already installed google-chrome but I prefer chromium :) I did not know the reason :)

**Comment by bil-elmoussaoui** [comment] 2015-08-13 10:49
My question was not to use Chrome instead of Chromuim. But just to try the script if everything works fine. i will try to fix the issue with Chromuim asap

**Comment by wa4557** [comment] 2015-08-13 13:47
I cannot confirm this: for me chromium and chrome both work as intended? For both the new and correct icon is displayed

**Comment by wa4557** [comment] 2015-08-13 14:00
The hangouts icons are stored here `~/.config/{google-chrome/chromium}/Default/Extensions/nckgahadagoaajjgafhacjanaoiihapd/2015.513.1632.5_0/images_4/presence`

**Comment by bil-elmoussaoui** [comment] 2015-08-13 20:21
Thanks for testing it :) that will be a easy one to do

**Comment by bil-elmoussaoui** [comment] 2015-08-13 23:37
I added a support to Hangouts extension and requested the icons in Numix base, once they're added you can fix it easily ;)

![screenshot from 2015-08-14 01-20-18](https://cloud.githubusercontent.com/assets/7660997/9264294/f957cbc2-4224-11e5-82e4-0fcc87a95273.png)

But the google chrome icon is not fixed in my case :/ I've been trying to figure out why, and i think that the icons shown in your case @wa4557 are the one we fix using the script. if you take a look at the extracted folder you will find the google chrome indicator icon. But changing this icon does not change the indicator one :( 

Any ideas?

**Comment by wa4557** [comment] 2015-08-14 08:17
That's not the icon we are replacing with the script :( I've never seen this tray icon on my machine, how can I see this icon? Maybe the icons in `/opt/google/chrome/product_logo`? I can't test it because I'm not able to see this tray icon

**Comment by bil-elmoussaoui** [comment] 2015-08-14 08:44
Well, i have no idea how, i just installed Hangouts and this icon appears. I tried to change the icons `product_logo*` but that does not work :/

**Comment by wa4557** [comment] 2015-08-14 09:10
Mayb it is another icon in the `pak` file?

**Comment by bil-elmoussaoui** [comment] 2015-08-14 09:13
i found the icon, changing it does not change the indicator icon :/ maybe in an other pak file ?

**Comment by wa4557** [comment] 2015-08-14 09:13
7470 could be the corresponding icon ...

**Comment by bil-elmoussaoui** [comment] 2015-08-14 13:21
Tried to change it but does not work, i will try to update Chrome to the latest version & try again :P

**Comment by wa4557** [comment] 2015-08-14 13:54
There are two other Icons that could be the one :)

Bilal Elmoussaoui <notifications@github.com> schrieb am Fr., 14.08.2015,
15:21:

**Comment by bil-elmoussaoui** [comment] 2015-08-16 12:10
I didn't get the time to try it. @raknerak Hangouts icon is now fixed ;) just update Numix base and run the script again

**Comment by bil-elmoussaoui** [comment] 2015-08-16 13:06
I changed all the three icons, the indicator icon does not seem to show anything (empty icon) after a while the default icon showed again :( i asked a question here [How to change the ugly chrome/chromuim tray icon](http://askubuntu.com/questions/662129/how-to-change-the-ugly-chrome-chromuim-tray-icon)
Hope we can have an answer on how to deal with this ugly icon.

**Comment by bil-elmoussaoui** [comment] 2015-08-18 15:09
I putted a bounty on the question, hope we got an answer to this soon ;)

**Comment by wa4557** [comment] 2015-08-20 14:09
Hmm. There's also the resources.pak in the chrome folder with icons 8000 8001 and 8002 the same as the icon in question. Again cannot test it because the icon doesn't show up on my machine :)

**Comment by bil-elmoussaoui** [comment] 2015-08-20 14:14
I will test that this week-end

**Comment by bil-elmoussaoui** [comment] 2015-08-29 07:58
Fixed in my latest commit :D the icon was in resources.pak, the icon name was 8002.png ;)

**Closed by bil-elmoussaoui** 2015-08-29 07:58 UTC
Labels: bug
