### ISSUE TITLE
sni-qt Ubuntu 16.10 dependency failure

### ISSUE THREAD

**Issue by yalok** [bil-elmoussaoui/Hardcode-Tray#210] opened 2016-11-13 18:06 UTC
Hi

Here is an installation issue:
```
sudo add-apt-repository ppa:varlesh-l/hardcode-tray
sudo apt update
sudo apt install --reinstall sni-qt hardcode-tray
 Patched sni-qt and hardcode-tray script.

SOURCES:
https://launchpad.net/~cybre/+archive/ubuntu/sni-qt-eplus
https://github.com/bil-elmoussaoui/Hardcode-Tray
 More info: https://launchpad.net/~varlesh-l/+archive/ubuntu/hardcode-tray
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpurmayunw/pubring.gpg' created
gpg: /tmp/tmpurmayunw/trustdb.gpg: trustdb created
gpg: key 1755F28E80AC0F06: public key "Launchpad PPA for varlesh" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
Get:1 http://mirror.as43289.net/ubuntu yakkety InRelease [247 kB]
Get:2 http://mirror.as43289.net/ubuntu yakkety-updates InRelease [94.5 kB]                                                                              
Get:3 http://mirror.as43289.net/ubuntu yakkety-backports InRelease [92.2 kB]                                                    
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                                    
Hit:5 http://archive.canonical.com/ubuntu yakkety InRelease                                                                     
Hit:6 http://ppa.launchpad.net/nilarimogard/webupd8/ubuntu yakkety InRelease                  
Get:7 http://mirror.as43289.net/ubuntu yakkety-security InRelease [93.3 kB]                   
Get:8 http://mirror.as43289.net/ubuntu yakkety-proposed InRelease [95.7 kB]                              
Hit:9 http://dl.google.com/linux/chrome/deb stable Release                                               
Hit:10 http://ppa.launchpad.net/noobslab/icons/ubuntu xenial InRelease                                   
Hit:11 http://ppa.launchpad.net/numix/ppa/ubuntu yakkety InRelease
Hit:12 http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu yakkety InRelease
Get:13 http://ppa.launchpad.net/varlesh-l/hardcode-tray/ubuntu yakkety InRelease [18.1 kB]
Ign:14 http://ppa.launchpad.net/varlesh-l/papirus-pack/ubuntu xenial InRelease
Hit:15 http://ppa.launchpad.net/wine/wine-builds/ubuntu yakkety InRelease
Get:18 http://ppa.launchpad.net/varlesh-l/hardcode-tray/ubuntu yakkety/main amd64 Packages [848 B]
Get:19 http://ppa.launchpad.net/varlesh-l/hardcode-tray/ubuntu yakkety/main i386 Packages [848 B]
Get:20 http://ppa.launchpad.net/varlesh-l/hardcode-tray/ubuntu yakkety/main Translation-en [312 B]
Reading package lists... Done          
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 hardcode-tray : Depends: sni-qt (= 0.2.8-0~81~ubuntu14.10) but 0.2.8-0~81~ubuntu16.10 is to be installed
E: Unable to correct problems, you have held broken packages.


```

**Comment by bil-elmoussaoui** [comment] 2016-11-13 18:14
@yalok I'm not the maintainer of the PPA and i don't use Ubuntu neither.. @varlesh is the maintainer of the PPA. I will ping him here and we will see what he will say :) 
@varlesh can you take a look at this?

**Comment by varlesh** [comment] 2016-11-13 19:24
@yalok Fixed. Please update packages database and install after a few minutes.

**Comment by varlesh** [comment] 2016-11-13 19:30
@yalok Please test hardcode-tray (and sni-qt) on Ubuntu 16.10, because now right work confirmed on Ubuntu 16.04 only.

**Comment by bil-elmoussaoui** [comment] 2016-11-14 13:21
@yalok reopen if you still have the same issue. Closing.

**Closed by bil-elmoussaoui** 2016-11-14 13:21 UTC
