### ISSUE TITLE
Request for BOINC icon

### ISSUE THREAD

**Issue by alienzj** [bil-elmoussaoui/Hardcode-Tray#448] opened 2017-09-29 07:56 UTC
Can you please add json file for BOINC？

**Comment by bil-elmoussaoui** [comment] 2017-09-29 08:01
It was already reported before. The icon is hardcoded on the binary file and there's no easy way to replace it :(

**Comment by bil-elmoussaoui** [comment] 2017-10-06 13:06
Duplicate of #145

**Closed** 2017-10-06 13:06 UTC
