### ISSUE TITLE
Rambox Not Fixed

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#480] opened 2018-01-13 10:38 UTC
### Specifications
- Hardcode-Tray version : 4.2
- Distribution : Fedora 27
- Gtk version : 3.22
- Inkscape version : 0.92.2 (5c3e80d, 2017-08-06)
- Application name :  Rambox
- Application version : 0.5.13

### Expected behavior and actual behavior
Expected: HC-T detects Rambox and changes the tray icon, actually doesn't detect it's installed. Location is still `/opt/Rambox/`.

### Steps to reproduce the problem
1. Fresh install of the above software
2. Run `sudo hardcode-tray` 
3. Or run `sudo hardcode-tray --only rambox --path /opt/Rambox/`

**Comment by bil-elmoussaoui** [comment] 2018-01-13 10:48
I have just tried the latest Rambox version and it works correctly for me. Can you copy/paste the logs? 
No need to specify --path in this case.

**Comment by terencode** [comment] 2018-01-13 14:49
@bil-elmoussaoui I'm also unable to apply it. What logs do you want?

**Comment by bil-elmoussaoui** [comment] 2018-01-13 14:55
They are stored on /tmp/Hardcode-Tray/

**Comment by terencode** [comment] 2018-01-13 15:29
Here you go: 
[13-01-2018_16-24-53.log](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1628466/13-01-2018_16-24-53.log)

Note: I'm using Arch Linux, rambox installed from the [AUR](https://aur.archlinux.org/packages/rambox/).

**Comment by bil-elmoussaoui** [comment] 2018-01-13 16:03
@Foggalong Where did you get the package from?

@terencode Can you try using the latest master version? Should be fixed in my latest commit 👍

**Comment by Foggalong** [comment] 2018-01-13 16:06
@bil-elmoussaoui I actually tested with two; the appimage and the rpm from the latest version on GH.

**Comment by bil-elmoussaoui** [comment] 2018-01-13 16:15
@Foggalong the appimage could not be patched at the moment... Its a sandboxed format ! 
I just tried the rpm and it works correctly  fine

**Comment by Foggalong** [comment] 2018-01-13 16:19
@bil-elmoussaoui On Fedora? This is my log 😢

[13-01-2018_16-24-53.log](https://github.com/bil-elmoussaoui/Hardcode-Tray/files/1628493/13-01-2018_16-24-53.log)

**Comment by terencode** [comment] 2018-01-13 18:10
@bil-elmoussaoui I can't try it, I get this when trying to apply:
```
Traceback (most recent call last):
  File "/usr/bin/hardcode-tray", line 119, in <module>
    App.execute()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 113, in execute
    apps = App.get_supported_apps()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/app.py", line 103, in get_supported_apps
    application_data = Parser(db_file)
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 47, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 93, in _read
    self._parse_icons(data["icons"])
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/parser.py", line 125, in _parse_icons
    icon = Icon(icons[icon])
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/icon.py", line 38, in __init__
    self._read()
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/icon.py", line 80, in _read
    self.icon_size = self.get_icon_size(App.icon_size())
  File "/usr/lib/python3.6/site-packages/HardcodeTray/modules/icon.py", line 102, in get_icon_size
    multiple = int(icon_name[1].split("x")[0])
ValueError: invalid literal for int() with base 10: '1.25'

```

**Comment by bil-elmoussaoui** [comment] 2018-01-13 18:18
Somehow there was an issue that I didn't seen before. But I have fixed that. You can pull the latest commit and build it. Otherwise you can try with `sudo -E hardcode-tray --only rambox --apply`

**Comment by terencode** [comment] 2018-01-13 18:19
@bil-elmoussaoui nice thanks I was going to add it was introduced with e9730bc26738e5a79ad9cf28058894d76a8369ca but was faster ;)

**Comment by terencode** [comment] 2018-01-13 18:22
@bil-elmoussaoui Everything working for me!

**Comment by bil-elmoussaoui** [comment] 2018-01-13 18:23
@terencode Perfect! Enjoy using a beautiful desktop :+1:

**Comment by bil-elmoussaoui** [comment] 2018-01-13 18:24
@Foggalong The icons are stored in `/opt/Rambox/resources/app.asar` Can you make sure it's the case?

**Comment by Foggalong** [comment] 2018-01-13 18:36
Yup :+1:
![2018-01-13-183625_1920x1080_scrot](https://user-images.githubusercontent.com/5920259/34908947-b1ee1564-f890-11e7-822e-685643a28ae7.png)

**Comment by bil-elmoussaoui** [comment] 2018-01-13 18:41
@Foggalong Can you please run `sudo -E hardcode-tray --only rambox.electron,rambox --apply`? Or just add the `hardcode-tray.json` to `$HOME/.config/` and put this content on it 
```
{ 	
    "icons": {
        "theme": "Numix",
        "size": 24
}
}
```
This will ensure that the Numix theme will be used with 24 icons size instead of trying to detect it automatically. This will allow you to avoid settings `--theme` and `--size` argument every time. 

Other configurations are possible, see here https://github.com/bil-elmoussaoui/Hardcode-Tray/blob/master/data/config.json

**Comment by Foggalong** [comment] 2018-01-13 18:54
Hey look, our old friend is back!

![2018-01-13-185121_1920x1080_scrot](https://user-images.githubusercontent.com/5920259/34909075-c306475c-f892-11e7-89d9-02ab8f6ca546.png)

Thankfully disappeared after restarting Rambox. Running `sudo -E hardcode-tray --only rambox.electron,rambox --apply` worked with the same HC-T version as the start, not the latest git, and without doing the thing about adding the `hardcode-tray.json` to `$HOME/config/`.

![2018-01-13-185415_264x34_scrot](https://user-images.githubusercontent.com/5920259/34909111-2c517a1a-f893-11e7-91e9-67334c9f69c3.png)


What does that mean the issue is? Detecting Rambox?

**Comment by bil-elmoussaoui** [comment] 2018-01-13 18:59
@Foggalong Nop the issue is about detecting the current theme :) if you run it using `sudo hardcode-tray` the theme won't be detected currently as the `-E` flag allows reading the values of the current user settings correctly :)
+ You should never run hardcode-tray and the application is open :p especially with electron apps as we replace stuff on a binary  file ;)

**Comment by Foggalong** [comment] 2018-01-13 19:13
Ah okay. Any thoughts on the theme detection / logs you need?

**Comment by bil-elmoussaoui** [comment] 2018-01-13 19:24
Just what DE you're using?

**Comment by Foggalong** [comment] 2018-01-13 19:44
Still XFCE/i3 :)

**Comment by bil-elmoussaoui** [comment] 2018-01-16 13:42
I will refactor that part of the code as of the next version. This is not an issue at all, but it needs some improvements as part of #397. So if you run the code without root permissions it should work as expected for detecting the system :)
I'm going to close this as the Rambox app works as expected after all

**Closed by bil-elmoussaoui** 2018-01-16 13:42 UTC

**Comment by Foggalong** [comment] 2018-01-16 14:01
@bil-elmoussaoui Thinking back, didn't there use to be a warning if you ran the script without the required `-E` flag?

**Comment by bil-elmoussaoui** [comment] 2018-01-17 23:52
There wasn't, we can't detect that :( At least, I'm not aware of that
