### ISSUE TITLE
sni-qt recommended in the README is out of date

### ISSUE THREAD

**Issue by Foggalong** [bil-elmoussaoui/Hardcode-Tray#40] opened 2015-07-03 17:37 UTC
needs either updating (do you manage it?) or switching to this one https://answers.launchpad.net/~cybre/+archive/ubuntu/elementaryplus

**Comment by bil-elmoussaoui** [comment] 2015-07-03 17:38
i don't know if i should create a ppa and build the latest sni-qt version

**Comment by Foggalong** [comment] 2015-07-03 17:39
Up to you! You could make it a hardcode-tray PPA too :)

**Comment by wa4557** [comment] 2015-07-03 17:41
I think the script turns out to be really useful (and I think it's also very well written) so a PPA would be great :)

**Comment by Foggalong** [comment] 2015-07-03 17:43
The PPA mentioned above doesn't actually work on Ubuntu 15.04 so a PPA just for sni-qt and the hc-tray would be awesome.

**Comment by bil-elmoussaoui** [comment] 2015-07-03 17:55
I will try to create a ppa as soon as possible

**Comment by Foggalong** [comment] 2015-07-03 20:21
Am I right in thinking I can't use this on 15.04 without the sni-qt?

**Comment by bil-elmoussaoui** [comment] 2015-07-03 20:24
You can download the deb file for 14.04 and install it in 15.04 (already tried it on 14.10) And yeah, you will need sni-qt

**Comment by bil-elmoussaoui** [comment] 2015-07-03 23:04
This is fixed now, i used a new ppa. I might create a new one soon but at the moment i will keep this in the readme

**Comment by Foggalong** [comment] 2015-07-05 13:43
I've ran the script and the output says ownCloud is fixed but it's still showing up in the panel unthemed. Is an icon cache refresh needed?

**Comment by wa4557** [comment] 2015-07-05 13:47
@Foggalong. Are the correct icons in `.local/share/sni-qt/icons/`? It works for me...

**Comment by Foggalong** [comment] 2015-07-05 13:51
I don't even have that folder on my computer :/ the script threw no errors either

**Comment by wa4557** [comment] 2015-07-05 13:54
I guess the problem is that the folder has to be created beforehand. I'll create a PR for that

**Comment by bil-elmoussaoui** [comment] 2015-07-05 14:44
@Foggalong can you try now?

**Comment by Foggalong** [comment] 2015-07-05 15:19
Yeah, still not working

**Comment by wa4557** [comment] 2015-07-05 15:20
but the icons and the folder are now there, right?

**Comment by Foggalong** [comment] 2015-07-05 15:21
nope :(

**Comment by wa4557** [comment] 2015-07-05 15:22
You sure you running the latest version? oO

**Comment by bil-elmoussaoui** [comment] 2015-07-05 15:23
@Foggalong can you look if there's any folder of ```sni-qt``` somewhere else?

**Comment by Foggalong** [comment] 2015-07-05 15:23
Yeah, freshly cloned

**Comment by wa4557** [comment] 2015-07-05 15:24
This is superweird, at least the folder should be created

**Comment by Foggalong** [comment] 2015-07-05 15:25
![screenshot_2015-07-05_16-24-41](https://cloud.githubusercontent.com/assets/5920259/8512236/654a08ca-2332-11e5-9f2a-cee4c01e95da.png)

**Comment by bil-elmoussaoui** [comment] 2015-07-05 15:28
@Foggalong install the 32bits version too

**Comment by wa4557** [comment] 2015-07-05 15:29
I don't have any patched version of sni-qt installed, and this folder still is being created. @Foggalong the success message is still being displayed?

**Comment by Foggalong** [comment] 2015-07-05 15:33
yeah :/

**Comment by wa4557** [comment] 2015-07-05 15:35
What does this give for you in a python console?
```
userhome = path.expanduser('~' + getlogin())
```
if this gives your home folder I'm officially out of ideas

**Comment by wa4557** [comment] 2015-07-05 15:49
@Foggalong it really really should work now. Can you try again?

**Comment by Foggalong** [comment] 2015-07-05 16:24
Yeah, it gave `/home/josh`

**Comment by Foggalong** [comment] 2015-07-05 16:25
aww yis
![screenshot_2015-07-05_17-25-34](https://cloud.githubusercontent.com/assets/5920259/8512444/dea45b1e-233a-11e5-889b-ebc813a5b62a.png)

**Comment by bil-elmoussaoui** [comment] 2015-07-05 16:26
@Foggalong can you share the content of ```.local/share/sni-qt/icons```?

**Comment by Foggalong** [comment] 2015-07-05 16:35
![screenshot_2015-07-05_17-35-08](https://cloud.githubusercontent.com/assets/5920259/8512476/3263b294-233c-11e5-84a9-c65ca4219f84.png)

**Comment by bil-elmoussaoui** [comment] 2015-07-05 16:36
Everything works fine :P did the indicator shows using the monochrome indicator?

**Comment by Foggalong** [comment] 2015-07-05 16:39
nope :(

**Comment by bil-elmoussaoui** [comment] 2015-07-05 16:40
can you create a new folder in ```.local/share/sni-qt/icons/``` rename the folder to ```owncloud``` and copy those icons there, close owncloud and reopen it again?

**Comment by Foggalong** [comment] 2015-07-05 16:52
No effect. The permissions were also set to root for the `/sni-qt` folder and fiddling with that similarly did nothing

**Comment by bil-elmoussaoui** [comment] 2015-07-05 17:41
@Foggalong the permission issue should be fixed now, i'm trying to find out why the icons are still ugly

**Comment by bil-elmoussaoui** [comment] 2015-07-05 20:11
I think that i found the issue , the icons are wrong :P I'm going to talk about this with elementaryPlus team and see what we will come with! We can try with skype and megasync icons once they're added to Numix base

**Comment by bil-elmoussaoui** [comment] 2015-07-05 21:44
@Foggalong I have found how to handle those sni-qt icons :P can you share the content of ```/tmp/sni-qt_owncloud_*-*/``` ? Also the version of ```owncloud-client```

**Comment by Foggalong** [comment] 2015-07-06 00:10
/tmp files [here](https://github.com/bil-elmoussaoui/Hardcode-Tray/issues/40#issuecomment-118632515) version is 1.7-lotsofstuff

**Comment by bil-elmoussaoui** [comment] 2015-07-06 02:06
and a screenshot or just a download link of the folder

**Comment by bil-elmoussaoui** [comment] 2015-07-08 00:00
I'm closing this issue as the sni-qt is updated now, @Foggalong feel free to open a new issue with the informations needed to fix your owncloud indicator issue

**Closed by bil-elmoussaoui** 2015-07-08 00:00 UTC

**Comment by Foggalong** [comment] 2015-07-08 00:42
Gotchya
