### ISSUE TITLE
Telegram `No apps to fix!`

### ISSUE THREAD

**Issue by conformist-mw** [bil-elmoussaoui/Hardcode-Tray#459] opened 2017-11-12 19:26 UTC
### Specifications
- Hardcode-Tray version : `4.1`
- Distribution : `ubuntu xenial`
- Gtk version : `3.18`
- Sni-qt version: `0.2.7+20161212~11~ubuntu16.04.1`
- Application name :  `telegram`
- Application version : `1.1.23`

### Expected behavior and actual behavior
Change icons but `No apps to fix!`
### Steps to reproduce the problem
installation path: `/opt/telegram/{Telegram,Updater}`
files location: `${HOME}/.local/share/TelegramDesktop`
run cmd:
`sudo hardcode-tray --only telegram --path /home/conformist/.local/share/TelegramDesktop/`
and without `path` the same result: `No apps to fix!`
Haven't a clue what I did wrong.

**Comment by bil-elmoussaoui** [comment] 2017-11-12 20:00
Can you please paste the whole output on the terminal with the rest of the information printed by Hardcode-Tray?

**Comment by conformist-mw** [comment] 2017-11-12 20:29
```bash
 ~ sudo hardcode-tray --only telegram --path /home/conformist/.local/share/TelegramDesktop/
Welcome to Hardcode-Tray!
Desktop Environment: Other
Scaling Factor: 1
Icon Size: 22
Icon Theme: breeze
Conversion Tool: ImageMagick
To Do: Telegram
1 - Apply
2 - Revert
3 - Clear Backup Cache
Please choose: 1
Applying now..


No apps to fix!

Done, Thank you for using the Hardcode-Tray fixer!
```

**Comment by bil-elmoussaoui** [comment] 2017-11-12 21:17
The problem is the icon theme is not detected correctly on your distro.
You can use `--theme` argument. See hardcode-tray --help.
Closing.

**Closed by bil-elmoussaoui** 2017-11-12 21:17 UTC

**Comment by conformist-mw** [comment] 2017-11-13 14:25
@bil-elmoussaoui Okay, but I'm confused. I use `Breeze` icon theme and adding to command `--theme breeze` has no any effect, still `No apps to fix`, no changes.

**Comment by bil-elmoussaoui** [comment] 2017-11-13 16:58
Hardcode-tray uses the icons provided by the theme... So we won't have to ship too many icons.
Breeze doesn't support those icons so it won't work; you need to use something else like Numix or Papirus ;)
